version: "3.9"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "25251:3000" # map port 3000 ของ container -> 25251 ของ host
    environment:
      NODE_ENV: production
    # volumes:
    #   - .:/app  # Disable volume for production to use built assets
    restart: unless-stopped
